name: Sync README

on:
  push:
    branches:
        - master
    paths:
      - 'README.md'

jobs:
  sync-readme:
    name: Sync README
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: "Syncing README"
        run: |
          # Sync the top-level README.md with the one in the addon package
          yarn docs:readme
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add ./packages/ember-lifeline/README.md
          git commit -m "Syncing README.md with addon readme"
          git push origin $GITHUB_BASE_REF
